# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AnggaR96s
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_display: columns
          config_octicon: yes
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 8
          plugin_code_load: 200
          plugin_code_visibility: public
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 7.5
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_other: yes
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 7
          plugin_languages_recent_load: 200
          plugin_languages_sections: most-used
          plugin_languages_threshold: 1%
          filename: "profile-left.svg"

      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: AnggaR96s
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_display: columns
          config_octicon: yes
          config_timezone: Asia/Jakarta
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 6
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_url: .user.website
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: DeathRhythm
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_limit: 0
          plugin_people_shuffle: yes
          plugin_people_size: 22
          plugin_people_types: followers, following
          filename: "profile-right.svg"
